name: Build Android App and Magisk Module

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Build Android app
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.0.2'
        arguments: assembleDebug
        cache-disabled: true
    - name: Package Magisk module
      run: zip -r magic_cam_spoofer.zip magisk_module
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MagicCamApp-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Magisk module artifact
      uses: actions/upload-artifact@v4
      with:
        name: MagicCamSpoofer
        path: magic_cam_spoofer.zip

    - name: Commit artifacts to repository
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        mkdir -p artifacts
        cp app/build/outputs/apk/debug/app-debug.apk artifacts/MagicCamApp-debug.apk
        cp magic_cam_spoofer.zip artifacts/MagicCamSpoofer.zip
        git add artifacts/MagicCamApp-debug.apk artifacts/MagicCamSpoofer.zip
        git commit -m "Add build artifacts [skip ci]"
        git push
